#!/bin/bash

curl -z BuildTools.jar -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

MINECRAFT_VERSION=1.16.5

mkdir -p test_server/{$MINECRAFT_VERSION,build_tools}
cd test_server/build_tools || exit 1

java -jar ../../BuildTools.jar --compile-if-changed --rev "$MINECRAFT_VERSION" --output-dir "../$MINECRAFT_VERSION/"